# Generated by Django 5.1 on 2024-08-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_note_id_alter_profile_id_alter_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('subject', models.CharField(choices=[('Compiler', 'Compiler'), ('MM', 'MM'), ('Java', 'Java'), ('SPM', 'SPM'), ('BRM', 'BRM')], max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
